### ISSUE TITLE
Investigate why the implschemaregistry.MustNew function is not using one of its parameters

### ISSUE THREAD

**Issue by victormn** [arquivei/foundationkit#98]
`MustNew` it not using `httpClient` in:

``` golang
// MustNew returns a new valid schemaregistry.Repository but panics in case on an error
func MustNew(url string, httpClient *http.Client) schemaregistry.Repository {
	const op = errors.Op("implschemaregistry.MustNew")

	if url == "" {
		panic(errors.E(op, "missing url"))
	}

	if !strings.HasSuffix(url, "/") {
		url += "/"
	}

	return &repository{
		getSchemaByIDURL: url + "schemas/ids/%d",
		getIDBySchemaURL: url + "subjects/%s",
	}
}
```

https://github.com/arquivei/foundationkit/blob/master/schemaregistry/implschemaregistry/repository.go

**Comment by eric-reis** [comment]
It seems that the `MustNew` function was expecting an instance of `http.Client` to use, since the instance can be configured with behaviors such as Timeout as the developer needs.

However, the implementation is using `httpResponse, err := http.Get(fullURL)` to do a HTTP request. I believe the code should be changed to use `http.Client` instead
